# This is a basic workflow to help you get started with Actions

name: firsttest

env:
  MY_WORK_DIR: /home/runner/test-amp
  
  
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      - name: setup env
        run: |
          env
          mkdir ${{env.MY_WORK_DIR}}
          cd ${{env.MY_WORK_DIR}}
          wget https://raw.githubusercontent.com/IgorSchittekat/MultiProject/main/run.sh
          chmod +x run.sh
      - name: clone library
        run: |
          git clone "https://github.com/$GITHUB_REPOSITORY"
          ls
          ls ${{ github.event.repository.name }}
        working-directory: ${{env.MY_WORK_DIR}}
      - name: run tests
        working-directory: ${{env.MY_WORK_DIR}}      
        run: |
          cp ./${{ github.event.repository.name }}/users.txt .
          ./run.sh
          ls
          ls ${{ github.event.repository.name }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{env.MY_WORK_DIR}}/${{ github.event.repository.name }}/htmlcov
